# Permalinks
#
permalink:           pretty

# Setup
title:               Encore
tagline:             'Data Management System'
description:         'Encore is a MATLAB based data management system for scientists.'
url:                 http://encore-dms.github.io
baseurl:             ''
usergroup:           https://groups.google.com/forum/#!forum/symphony-das

# About/contact
author:
  name:              Encore-DMS
  url:               http://encore-dms.github.io
  email:             symphony-das@googlegroups.com

# Custom vars
version:             0.0.0.0

github:
  repo:              https://github.com/Encore-DMS/encore
  org:               https://github.com/Encore-DMS

gitbook:
  book:              https://cafarm.gitbooks.io/encore
